### ISSUE TITLE
Worker with ZeroMQ does not work on Windows with default configuration

### ISSUE THREAD

**Issue by raidzin** [taskiq-python/taskiq#524]
Asynchronous ZeroMQ does not work on **Windows** with default `asyncio.WindowsProactorEventLoopPolicy`. 

It raises:

```
RuntimeError: Proactor event loop does not implement add_reader family of methods required for zmq. zmq will work with proactor if tornado >= 6.1 can be found.
Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` or install 'tornado>=6.1' to avoid this error.
```

If I install `tornado` as required by the exception, then the worker starts, but there is a **warning** that I need to configure the eventloop.

```
RuntimeWarning: Proactor event loop does not implement add_reader family of methods required for zmq. Registering an additional selector thread for add_reader support via tornado. Use `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to avoid this warning.        
  self._get_loop()
```

Adding `asyncio.set_event_loop_policy(WindowsSelectorEventLoopPolicy())` to the application code has no effect for worker

**Comment by raidzin** [comment]
@s3rius, I see two ways to solve this problem:
1. We can add `tornado` as a _platform-specific_ dependency when we use the optional `zmq` dependency. With this, the worker will start, but the warning will remain
2. We can add a check that `pyzmq` is installed and `os.name == 'nt'` and then change the default `EventLoopPolicy` to `WindowsSelectorEventLoopPolicy` when worker starts

To be honest, I can't say exactly what side effects the second option might have, but I tested on pure `pyzmq` and it worked without a `tornado`

**Comment by danfimov** [comment]
The second option seems more optimal to me. I don't have Windows handy to test it myself, so if you try it out and come up with a fix, I'd be happy to review it)
